name: tests
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  unitary-tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt update
          sudo DEBIAN_FRONTEND=noninteractive apt install -y python3 python3-yaml
      - name: Test remove_common
        run: |
          cd remove_common
          ./unittests.py
